#!/usr/bin/env bash
# Personal dotfiles installer. Safe to re-run.
#
# Machine role comes from the untracked ~/.dotfiles-profile:
#   ROLE=personal-mac | work-mac | vps
# Anything already at a target path is moved to ~/.dotfiles-backup/<timestamp>/ before linking.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROFILE="$HOME/.dotfiles-profile"
BACKUP="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }
die() { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

# --- role / OS -------------------------------------------------------------------------------
[ -f "$PROFILE" ] || die "missing $PROFILE (create it with ROLE=personal-mac|work-mac|vps)"
# shellcheck disable=SC1090
. "$PROFILE"
case "${ROLE:-}" in
  personal-mac | work-mac | vps) ;;
  *) die "invalid ROLE='${ROLE:-}' in $PROFILE" ;;
esac
case "$(uname -s)" in
  Darwin) OS=darwin ;;
  Linux) OS=linux ;;
  *) die "unsupported OS $(uname -s)" ;;
esac
say "role=$ROLE os=$OS"

# --- helpers ---------------------------------------------------------------------------------
# Move an existing path into the backup dir, keeping its $HOME-relative location.
backup() {
  local path="$1" rel dest
  rel="${path#"$HOME"/}"
  dest="$BACKUP/$rel"
  mkdir -p "$(dirname "$dest")"
  mv "$path" "$dest"
  note "backed up $path -> $dest"
}

# link <repo-relative source> <absolute target>
link() {
  local src="$DOTFILES/$1" dst="$2"
  [ -e "$src" ] || die "link source missing: $src"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
    return 0
  fi
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    backup "$dst"
  fi
  mkdir -p "$(dirname "$dst")"
  ln -s "$src" "$dst"
  note "linked $dst -> $src"
}

# retire <absolute path>: move a file that must no longer exist (e.g. an overriding config) to backup.
retire() {
  if [ -e "$1" ] || [ -L "$1" ]; then
    backup "$1"
  fi
}

# vscode_file <settings|keybindings>
# Without a machine-local file: symlink the repo file.
# With ~/.config/vscode/<name>.local.json: write a generated file = repo file + local file
# (objects deep-merged, arrays appended). If the generated file was edited since the last run
# (e.g. from the VS Code UI), it is backed up before being regenerated.
vscode_file() {
  local name="$1"
  local src="$DOTFILES/vscode/$name.json"
  local dst="$APP_SUPPORT/Code/User/$name.json"
  local loc="$HOME/.config/vscode/$name.local.json"
  local state="$HOME/.local/state/dotfiles/vscode-$name.sha"
  if [ ! -f "$loc" ]; then
    link "vscode/$name.json" "$dst"
    return 0
  fi
  local tmp header
  tmp="$(mktemp)"
  header="GENERATED by ~/.dotfiles/install.sh from ~/.dotfiles/vscode/$name.json + $loc.
Edit those files and re-run install.sh; changes made here are overwritten (a backup is kept)."
  python3 "$DOTFILES/lib/jsonc_merge.py" "$src" "$loc" "$header" >"$tmp"
  chmod 644 "$tmp"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
    rm "$dst"
  elif [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then
    rm "$tmp"
    return 0
  elif [ -e "$dst" ] || [ -L "$dst" ]; then
    if [ ! -f "$state" ] || [ "$(shasum "$dst" | cut -d' ' -f1)" != "$(cat "$state")" ]; then
      note "WARNING: $dst was changed outside install.sh; backing it up. Move wanted changes into the repo or local file."
      backup "$dst"
    fi
  fi
  mkdir -p "$(dirname "$dst")" "$(dirname "$state")"
  mv "$tmp" "$dst"
  shasum "$dst" | cut -d' ' -f1 >"$state"
  note "generated $dst (repo + local)"
}

if [ "$OS" = darwin ]; then
  APP_SUPPORT="$HOME/Library/Application Support"
fi

# --- repo ------------------------------------------------------------------------------------
say "repo"
git -C "$DOTFILES" config core.hooksPath .githooks
chmod +x "$DOTFILES"/bin/* "$DOTFILES"/.githooks/*

# --- homebrew --------------------------------------------------------------------------------
# Personal Brewfile everywhere; the untracked ~/.Brewfile.local adds work-only packages.
# No upgrades and no cleanup: only installs what is missing. DOTFILES_SKIP_BREW=1 skips this.
if [ "$OS" = darwin ] && [ "${DOTFILES_SKIP_BREW:-0}" != 1 ]; then
  say "homebrew"
  BREW="$(command -v brew || true)"
  for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [ -n "$BREW" ] || { [ -x "$b" ] && BREW="$b"; }
  done
  [ -n "$BREW" ] || die "Homebrew missing. Install it from https://brew.sh, then re-run."
  for bf in "$DOTFILES/Brewfile" "$HOME/.Brewfile.local"; do
    [ -f "$bf" ] || continue
    if "$BREW" bundle check --no-upgrade --file="$bf" >/dev/null 2>&1; then
      note "$bf: satisfied"
    else
      "$BREW" bundle install --no-upgrade --file="$bf"
    fi
  done
fi

# --- git -------------------------------------------------------------------------------------
say "git"
link git/gitconfig "$HOME/.gitconfig"
link git/ignore "$HOME/.config/git/ignore"
retire "$HOME/.gitignore_global"
[ -f "$HOME/.gitconfig.local" ] || note "no ~/.gitconfig.local (optional machine overrides)"

# --- shells --------------------------------------------------------------------------------
say "zsh / bash"
link zsh/zshenv "$HOME/.zshenv"
link zsh/zshrc "$HOME/.zshrc"
link bash/bashrc "$HOME/.bashrc"
link bash/bash_profile "$HOME/.bash_profile"
# Old startup files, prompt themes and shells that are no longer used.
for f in .zprofile .zlogin .zshrc.backup .zshrc.bak .p10k.zsh .config/fish; do
  retire "$HOME/$f"
done
# ~/.profile is still the login file for sh; on macOS it only held version-manager hooks.
[ "$OS" = darwin ] && retire "$HOME/.profile"

# --- gh --------------------------------------------------------------------------------------
say "gh"
# config.yml only; hosts.yml holds auth tokens and stays local.
link gh/config.yml "${XDG_CONFIG_HOME:-$HOME/.config}/gh/config.yml"

# --- tmux (no longer used) -------------------------------------------------------------------
retire "$HOME/.tmux.conf"

# --- neovim ----------------------------------------------------------------------------------
say "nvim"
link nvim "${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
# lua/local/ (gitignored) holds machine-only plugins/keymaps; lazy-lock.json is gitignored too.

# --- ghostty ---------------------------------------------------------------------------------
if [ "$OS" = darwin ]; then
  say "ghostty"
  link ghostty/config.ghostty "$HOME/.config/ghostty/config.ghostty"
  # The Application Support config overrides the XDG one, so it must go.
  retire "$APP_SUPPORT/com.mitchellh.ghostty/config.ghostty"
  retire "$APP_SUPPORT/com.mitchellh.ghostty/config"
fi

# --- lazygit ---------------------------------------------------------------------------------
say "lazygit"
if [ "$OS" = darwin ]; then
  link lazygit/config.yml "$APP_SUPPORT/lazygit/config.yml"
else
  link lazygit/config.yml "${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/config.yml"
fi

# --- herdr -----------------------------------------------------------------------------------
say "herdr"
link herdr/config.toml "$HOME/.config/herdr/config.toml"
link herdr/plugins.json "$HOME/.config/herdr/plugins.json"
# The helper scripts now live in ~/.dotfiles/bin; drop the old ~/.local/bin copies.
for s in herdr-equalize-panes herdr-worktree-tab; do
  [ -L "$HOME/.local/bin/$s" ] || retire "$HOME/.local/bin/$s"
done

# --- vs code ---------------------------------------------------------------------------------
if [ "$OS" = darwin ]; then
  say "vscode"
  for name in settings keybindings; do
    vscode_file "$name"
  done
fi

# --- xcode ---------------------------------------------------------------------------------
# Whole KeyBindings/ directory: Xcode saves by replacing files, which would break a file symlink.
if [ "$OS" = darwin ]; then
  say "xcode"
  link xcode/KeyBindings "$HOME/Library/Developer/Xcode/UserData/KeyBindings"
  "$DOTFILES/xcode/xcode.sh"
fi

# --- agents: skills --------------------------------------------------------------------------
# Own skills: one symlink per skill in ~/.agents/skills (Codex and other agents) and ~/.claude/skills.
# Other entries in those dirs (third-party or untracked skills) are left alone.
say "agent skills"
for dir in "$DOTFILES"/agents/skills/*/; do
  s="$(basename "$dir")"
  link "agents/skills/$s" "$HOME/.agents/skills/$s"
  link "agents/skills/$s" "$HOME/.claude/skills/$s"
done
# Third-party skills are restored, not vendored. Runs only when they are missing.
THIRD_PARTY_SKILLS=(code-review edit-article git-guardrails-claude-code grill-me grill-with-docs grilling
  handoff to-prd wait-what wayfinder writing-for-agents writing-great-skills)
missing=0
for s in "${THIRD_PARTY_SKILLS[@]}"; do [ -e "$HOME/.agents/skills/$s" ] || missing=1; done
if [ "$missing" = 1 ]; then
  if command -v npx >/dev/null 2>&1; then
    npx -y skills@latest add mattpocock/skills -g -y -a claude-code -a codex -s "${THIRD_PARTY_SKILLS[@]}"
  else
    note "npx missing: skipped third-party skills (mattpocock/skills)"
  fi
fi
# Dropped: find-skills; Codex's private copy of drive-screen (it reads ~/.agents/skills).
retire "$HOME/.agents/skills/find-skills"
retire "$HOME/.claude/skills/find-skills"
retire "$HOME/.codex/skills/drive-screen"

# --- agents: claude --------------------------------------------------------------------------
say "claude"
link agents/claude/settings.json "$HOME/.claude/settings.json"
link agents/claude/CLAUDE.md "$HOME/.claude/CLAUDE.md"
link agents/claude/statusline-command.sh "$HOME/.claude/statusline-command.sh"
link agents/claude/hooks "$HOME/.claude/scripts/hooks"
# Dropped: own agents/commands, claude-code-docs, jev-guard, the old enhanced statusline.
for p in .claude/agents .claude/commands .claude/statusline-enhanced.sh .claude-code-docs .agents/jev-guard; do
  retire "$HOME/$p"
done
if command -v claude >/dev/null 2>&1; then
  # User-scope MCP servers from agents/mcp.json (only the missing ones).
  while IFS=$'\t' read -r name json; do
    claude mcp get "$name" >/dev/null 2>&1 || claude mcp add-json -s user "$name" "$json" </dev/null
  done < <(python3 -c 'import json,sys
for n,s in json.load(open(sys.argv[1]))["mcpServers"].items(): print(n, json.dumps(s), sep="\t")' "$DOTFILES/agents/mcp.json")
fi

# --- agents: codex ---------------------------------------------------------------------------
say "codex"
# Seed-copy: Codex keeps writing machine state (project trust, hook hashes) into config.toml.
if [ ! -e "$HOME/.codex/config.toml" ]; then
  mkdir -p "$HOME/.codex"
  cp "$DOTFILES/agents/codex/config.toml" "$HOME/.codex/config.toml"
  note "seeded ~/.codex/config.toml"
fi
retire "$HOME/.codex/prompts"
# MCP servers from agents/mcp.json: append missing [mcp_servers.<name>] tables. Not `codex mcp add`,
# which blocks on an OAuth browser login; run `codex mcp login <name>` yourself when needed.
if [ -f "$HOME/.codex/config.toml" ]; then
  python3 - "$DOTFILES/agents/mcp.json" "$HOME/.codex/config.toml" <<'PY'
import json, sys, tomllib
servers = json.load(open(sys.argv[1]))["mcpServers"]
path = sys.argv[2]
have = tomllib.load(open(path, "rb")).get("mcp_servers", {})
add = [n for n in servers if n not in have]
if add:
    with open(path, "a") as f:
        for n in add:
            f.write(f'\n[mcp_servers.{n}]\nurl = {json.dumps(servers[n]["url"])}\n')
            print(f"    added codex MCP server {n} (log in with: codex mcp login {n})")
PY
fi

# --- agents: herdr state hooks ---------------------------------------------------------------
# The hook scripts are owned by herdr (`herdr integration install`), so they are not tracked.
if command -v herdr >/dev/null 2>&1; then
  for a in claude codex; do
    herdr integration status 2>/dev/null | grep -q "^$a: current" || herdr integration install "$a" </dev/null
  done
fi

say "done"
[ -d "$BACKUP" ] && note "backups in $BACKUP"
exit 0
